### ISSUE TITLE
"No Files" when accessing Files

### ISSUE THREAD

**Issue by naturalobject** [ismartcoding/plain-app#10]
I already granted storage permissions. Happens on both the phone app and the web interface.

**Comment by ismartcoding** [comment]
Could you please provide me with the device name, Android OS version, and app version for troubleshooting purposes? If possible, the screenshots will also be useful.

 - Device: [e.g. Pixel 4XL]
 - OS: [e.g. Android 13]
 - App Version: [e.g. 1.0.16]

**Comment by naturalobject** [comment]
Sorry for the delay.

Device: Galxy Note 9
OS: Android 10
App Version: 1.0.15 (14)

![](https://user-images.githubusercontent.com/130379566/233869515-1e22c99e-7b4b-422d-9d38-b60cb83b0164.png)

**Comment by naturalobject** [comment]
Issue still exists on version 1.0.16 (17)
