### ISSUE TITLE
Split APK Architectures

### ISSUE THREAD

**Issue by chromer030** [ismartcoding/plain-app#100]
**Is your feature request related to a problem? Please describe.**
Somehow, current single 100mb apk is too large.

**Describe the solution you'd like**
Please split release APK to each architecture (arm64, x86 etc) + the currenct universal apk (for fdroid).

**Describe alternatives you've considered**

**Additional context**

**Comment by ismartcoding** [comment]
You can check f-droid, it is already splitted. https://f-droid.org/packages/com.ismartcoding.plain
