### ISSUE TITLE
Error While Downloading

### ISSUE THREAD

**Issue by siddh-cyber** [ismartcoding/plain-app#101]
It showing network issue when I download file from Microsoft edge

**Screenshots**

![Screenshot_20230929_165439.jpg](https://github.com/ismartcoding/plain-app/assets/146439974/8a07baec-c3de-469b-9858-ae564ee9919d)

 - OS: Windows 11
 - Browser Microsoft Edge

**Comment by ismartcoding** [comment]
What is the APP version? Can you try if it is working on Chrome?

**Comment by siddh-cyber** [comment]
It is working with FDM(Free Download Manager) and Mozila Firefox, i will
try in chrome but I regularly using Microsoft edge so please try to fix
issue

**Comment by ismartcoding** [comment]
I don't have a windows machine to test. Can you check this article first? https://windowsreport.com/edge-couldnt-download

**Comment by ismartcoding** [comment]
Other users report that it works normally in the Edge browser.
