### ISSUE TITLE
the app crashes

### ISSUE THREAD

**Issue by Miserableee** [ismartcoding/plain-app#104]
In the recent update of the app, When I go to the message section, the app crashes for no particular reason. usually happens when I hold a message.
Device: Nokia 7.2
Android 11
App version: 1.2.10

**Comment by ismartcoding** [comment]
Fixed after upgraded the jetpack compose [1.6.0-rc01](https://developer.android.com/jetpack/androidx/releases/compose-ui#1.6.0-rc01)
