### ISSUE TITLE
feed : rss

### ISSUE THREAD

**Issue by imxade** [ismartcoding/plain-app#109]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
support to subscribe for xml links

**Comment by ismartcoding** [comment]
What does xml link mean? Can you give me some examples?

**Comment by imxade** [comment]
for example https://joyofcode.xyz/rss.xml

**Comment by ismartcoding** [comment]
What seems to be the problem? I'm able to see the full content of each RSS entry without any issues. Remember to enable the "Fetch content automatically" option if you want the app to retrieve the full content automatically.

![image](https://github.com/ismartcoding/plain-app/assets/92670034/35d8bd9c-be8c-4f0d-85a9-37527dc90b1b)
