### ISSUE TITLE
Color Picker for Custom Color

### ISSUE THREAD

**Issue by Niraj81** [ismartcoding/plain-app#114]
**Is your feature request related to a problem? Please describe.**
Not related to a problem but is an enhancement.

**Describe the solution you'd like**
I would like the custom color to be set by a color picker instead of only allowing user to input a hex value.

**Describe alternatives you've considered**
A color picker would be fine.

**Additional context**
I would like to work on this feature.

**Comment by Niraj81** [comment]
Hey @ismartcoding, Do I have the permission to do so?

**Comment by ismartcoding** [comment]
Yes, you can fork the project and modify the code and then create a pull request.
