### ISSUE TITLE
Hide "ID" column on feeds (desktop view)

### ISSUE THREAD

**Issue by analpi** [ismartcoding/plain-app#121]
The ID column on the list of feeds serves no apparent purpose, and only takes up space so that the titles of feed entries get squashed into a tiny little unreadable space. Can it be removed to make more room for the titles?

**Comment by Faserr** [comment]
Are you referring to the list in the notes view?

**Comment by Faserr** [comment]
Is it like this?
<img width="775" alt="image" src="https://github.com/ismartcoding/plain-app/assets/46740335/b6ea1ba8-3c69-469e-a309-53f3971da854">

**Comment by Faserr** [comment]
Ok, I'm sorry, I misunderstood "feeds".
