### ISSUE TITLE
Show phone notifications on PC

### ISSUE THREAD

**Issue by sid-the-sloth1** [ismartcoding/plain-app#122]
Greetings

Not really a problem, but a feature request that would be very helpful to me and maybe others too. Often, I am working or studying on my laptop, while my phone is on silent. I have KDE Connect installed, so that any notifications or calls on my phone, appear on my Laptop too. Now, I prefer PlainApp over KDE Connect for connecting my phone with PC, but since PlainApp does not have this notification sync, I have to use both apps. If you could kindly add this notification sync feature, it will be very helpful and completely end my dependence on KDE Connect.

I understand that if this feature is implemented it might be bit limited in comparison of KDE Connect, as PlainApp runs in browser. But kindly do consider and see if you feel this feature is something that you feel is worth investing time and energy into.

**Comment by ismartcoding** [comment]
Added in 1.2.13
