### ISSUE TITLE
ios端无法打开网页

### ISSUE THREAD

**Issue by Ignareo** [ismartcoding/plain-app#124]
**Describe the bug**
MIUI14上启动本软件，win上可以正常打开网页并使用，但是ios端打开网页后，无法登陆，提示“ 推荐使用最新版的Chrome浏览器”
http和https均不行，safari、edge、chrome、duckduckgo等浏览器均不行
ios设备为Ipad2021pro，m1芯片，ipados16

附上safari浏览器截图和alook浏览器的网页源代码
![3E355288-C41E-49D6-AC6A-F3300302BA1C](https://github.com/ismartcoding/plain-app/assets/56428448/99f0a1d1-c27e-4ba6-ae9e-fd44336899b4)
![8A2B3DEA-3325-4DD7-94EE-807C76938BAD](https://github.com/ismartcoding/plain-app/assets/56428448/05a273cf-c853-4ef3-ad88-b4cf91ab3b81)

**Comment by ismartcoding** [comment]
iPadOS还能再升级吗。https://github.com/material-components/material-web/issues/4451

**Comment by Ignareo** [comment]
> iPadOS还能再升级吗。[material-components/material-web#4451](https://github.com/material-components/material-web/issues/4451)

谢谢，升到ipados17后正常了
