### ISSUE TITLE
Regarding Download Speed!

### ISSUE THREAD

**Issue by Zombie-dev-1** [ismartcoding/plain-app#125]
I came from qrcp to this and I love the work but i noticed that i am not getting enough speed on downloads as on QRCP.But I still appreciate the work and hope there will be a fix didnt know it was a bug that why the enhancement tag.Thank You

**Comment by ismartcoding** [comment]
I conducted tests with QRCP and observed no discernible speed differences in the following scenarios:

1. Using the command `qrcp receive` on MacOS to receive a file uploaded from a phone. The file size was 69 MB, and the transfer took approximately 14.5 seconds.

2. Accessing the plainapp webpage on MacOS Chrome and downloading the 69 MB file. The download process completed in about 14 seconds in total.

**Comment by ismartcoding** [comment]
https://github.com/ismartcoding/plain-app/issues/152
