### ISSUE TITLE
Add ability to copy a phone number.

### ISSUE THREAD

**Issue by CakesTwix** [ismartcoding/plain-app#126]
**Is your feature request related to a problem? Please describe.**
Need to quickly copy a phone number to a PC. It is problematic when you can only get the phone number via USSD code (*111# for example)

**Describe the solution you'd like**
Add a button to the website to copy the number to the clipboard.
For USSD request in the settings you can specify your own code or make a list of matches. SIM Provider 1 == 154, SIM Provider 2 == 122, etc.

**Describe alternatives you've considered**
https://github.com/CakesTwix/PhoneCopy

**Additional context**
![image](https://github.com/ismartcoding/plain-app/assets/57946485/881f5f1d-c3d3-4b20-83c1-102934019191)

**Comment by ismartcoding** [comment]
Can you tell me in what scenarios this feature would be used? Typically, individuals have 1-2 phone numbers. Some phones allow users to view their own number in the contacts list, or individuals may already know their own phone number.

**Comment by CakesTwix** [comment]
@ismartcoding, I work with many sim cards and to avoid wasting time copying from the screen I made my own app, but yesterday I found yours which is perfect for me and my employees who can copy my number in parallel.

**Comment by ismartcoding** [comment]
I've implemented a device info page in the 1.2.15 version. Currently, it displays only one phone number since USSD is not universally supported by all phone providers. If you wish to include multiple phone numbers, your contribution of USSD codes to this project would be greatly appreciated.
