### ISSUE TITLE
App isn't supported anymore in my device

### ISSUE THREAD

**Issue by fireocta** [ismartcoding/plain-app#128]
![SmartSelect_20231209_144100_Google Play Store](https://github.com/ismartcoding/plain-app/assets/120381992/8fb1df5d-95f7-4a03-81bc-9037ea659254)

**Comment by ismartcoding** [comment]
What is your Android OS version and phone model?

**Comment by fireocta** [comment]
Product name Galaxy F13
Model name SM-E135F/DS
Android 13

**Comment by ismartcoding** [comment]
Can you check this article https://www.followchain.org/this-app-wont-work-for-your-device/?
