### ISSUE TITLE
Add Russian to :exchange

### ISSUE THREAD

**Issue by Wjxfi** [ismartcoding/plain-app#13]
**Describe the solution you'd like**
Add Russian to :exchange

**Describe alternatives you've considered**
If your currency provider does not support Russian, you can change to this open source alternative, built specifically for applications
https://github.com/Formicka/exchangerate.host

**Additional context**
this app has already done it:
https://www.f-droid.org/packages/de.salomax.currencies/
(it works just through https://exchangerate.host)

exchangerate.host with over 160 currencies

**Comment by ismartcoding** [comment]
https://github.com/ismartcoding/plain-app/releases/tag/v1.1.3
