### ISSUE TITLE
add PWA support

### ISSUE THREAD

**Issue by osbyrne** [ismartcoding/plain-app#130]
would be nice to have the
<img width="57" alt="image" src="https://github.com/ismartcoding/plain-app/assets/68084397/13ccd274-4de0-4487-9512-cacbde5850f1">
option

**Comment by ismartcoding** [comment]
Where can I find this icon?

**Comment by ismartcoding** [comment]
https://github.com/ismartcoding/plain-app/releases/tag/v1.2.16

**Comment by osbyrne** [comment]
good lord you fixed it in < 1 day
🙏 🎊
