### ISSUE TITLE
Please add favicon so that the bookmarks to my plainapp phone is distinctive

### ISSUE THREAD

**Issue by shodanx2** [ismartcoding/plain-app#135]
It would make the bookmark to plainapp on my bookmarks toolbar easier to find !

**Comment by ismartcoding** [comment]
The webpage has favicon.ico if you check the page source, what is your web browser and version?

**Comment by shodanx2** [comment]
Hello,

This is using firefox 121.0

Not sure what is going on.

I can see the favicon on the tab, but not toolbar & bookmark.


![2023-12-25 14_21_48-PlainApp — Mozilla Firefox](https://github.com/ismartcoding/plain-app/assets/10621885/26ab7a49-4b2f-4893-a5c0-ed2bbdc81dab)

**Comment by ismartcoding** [comment]
It is a common issue on Firefox. I'll address it when I find some time.
