### ISSUE TITLE
Http Server Failed on Android 11 (MIUI 12.1.2): Unable to Connect to Web on PC Section

### ISSUE THREAD

**Issue by SciC0der** [ismartcoding/plain-app#137]
**Issue Description:**

I encountered a problem with the PlainApp Android client when trying to access the web on PC section. The issue occurs consistently after the initial installation on Android 11 with MIUI 12.1.2.

**Error Message:**

```
Http server started failed. You need to force quit the app and then open it again.
```

**Steps to Reproduce:**

1. Install PlainApp on an Android device running Android 11 with MIUI 12.1.2.
2. Open the application for the first time.
3. Encounter the "Http server started failed" error.
4. Force quit the app and relaunch it.
5. Attempt to access the web on PC section.

**Expected Behavior:**

After force quitting and relaunching the app, the web on PC section should function correctly without any connection issues.

**Actual Behavior:**

Even after following the suggested steps, attempting to access the web on PC section results in a "The connection was reset" error when entering the IP in the browser.

**Additional Information:**

- Android Version: 11
- MIUI Version: 12.1.2
- Permissions: All permissions for the app are enabled.
- Tested on different devices and networks; the problem persists.

**Screenshots:**

![1](https://github.com/ismartcoding/plain-app/assets/154789383/8bedfc6e-c1c9-445b-b976-5da02cd3de9d)
![2](https://github.com/ismartcoding/plain-app/assets/154789383/64dfaaee-0959-4190-9924-a1b1e0f2bd0d)

**Comment by ismartcoding** [comment]
Can you try the latest version on github https://github.com/ismartcoding/plain-app/releases/tag/v1.2.22 and see if that will work?

If it still doesn't work, post the screenshot of "Web on PC" page.
