### ISSUE TITLE
translation capability for your app

### ISSUE THREAD

**Issue by Wjxfi** [ismartcoding/plain-app#14]
https://hosted.weblate.org/languages/en/homepage/

everyone uses it, it is now the easiest, fastest and most convenient site to translate, built for open source.

_free for open source applications_

By the way, the site itself is open source

alternative: crowdin.com. it is also very popular in open source projects, but it is closed source

**Comment by ismartcoding** [comment]
Support 12 languages now.

**Comment by ismartcoding** [comment]
I utilize ChatGPT for translating the text efficiently. Weblate and Crowdwin may take a longer time to complete the translation process from users.
