### ISSUE TITLE
the ability to choose your own password

### ISSUE THREAD

**Issue by Wjxfi** [ismartcoding/plain-app#15]
![0a288953-b3e6-48d2-b4b3-0a35db30de9a.jpg](https://user-images.githubusercontent.com/113500363/233800415-2389327d-c9f3-4873-9b8b-b4ac94265117.jpg)

I'm a thousand percent sure it's too small and can be cracked in a minute. I would like to enter a huge password myself.

'

or you could make a "change to HUGE password" button

And next to it will be a button to copy to the clipboard

password must be 120 characters

**Comment by ismartcoding** [comment]
As it has two-factor authentication, the current password length is enough.

**Comment by OddSobriquet** [comment]
Like what are you doing with the 120char password after you copied it to an unencrypted clipboard which probably doesn't get cleared after 10seconds?

While I agree that picking your own password should be an option offered, your request of a 120char passcode is ridiculous. I'd argue, your 120char code, which you need to send to your pc in someway (which is most likely not encrypted) has more vulnerabilities than this rememberable 6digit code...

**Comment by ismartcoding** [comment]
Added to 1.0.25
