### ISSUE TITLE
上传下载速度跑不满

### ISSUE THREAD

**Issue by redisviewer** [ismartcoding/plain-app#152]
如题文件管理时，上传下载速度跑不满，希望作者能优化一下，其余非常好用！

本地测试使用APP为HTTP File Server时可以跑满
运行环境：安卓14/澎湃OS
运行版本：1.2.29

**Comment by ismartcoding** [comment]
HTTP File Server是这个应用吗https://play.google.com/store/apps/details?id=slowscript.httpfileserver&hl=en_US

**Comment by redisviewer** [comment]
> HTTP File Server是这个应用吗https://play.google.com/store/apps/details?id=slowscript.httpfileserver&hl=en_US

恩是的，但这个app不是很稳定，整体来说ftpshare还是好用些

**Comment by ismartcoding** [comment]
已修复，数据传输 gzip压缩导致速率下降，https://github.com/ismartcoding/plain-app/commit/19caba002646bcc0f81be4b1f5681d731fb0aff6
