### ISSUE TITLE
Pure black / amoled / oled theme option

### ISSUE THREAD

**Issue by xusiai** [ismartcoding/plain-app#153]
I would appreciate an option to use a pure black theme. Since Android does not offer this as an option by default, a lot of applications add a separate in-app option to use a pure black background along with the material you accent; it would be nice to have this in the plain app as well.

**Comment by ismartcoding** [comment]
Tap the dark theme option -> AMOLED dark theme.

![image](https://github.com/ismartcoding/plain-app/assets/92670034/f6026048-9a91-42a8-90a4-a921ee8c7de3)

![image](https://github.com/ismartcoding/plain-app/assets/92670034/9ddd9c16-3ebd-4792-9012-760df023f1df)
