### ISSUE TITLE
Monochrome icon

### ISSUE THREAD

**Issue by xmha97** [ismartcoding/plain-app#156]
Please support the Android 13+ themed app icon feature.

![Screenshot_2024-02-24-02-02-10-028_de.mm20.launcher2.release.jpg](https://github.com/ismartcoding/plain-app/assets/23485114/09261fc3-96c9-4923-a4a5-928d9f28f30f)

**Comment by xmha97** [comment]
Thanks

**Comment by xmha97** [comment]
@ismartcoding I installed the latest version of the app but still this feature is not added.

![Screenshot_2024-04-02-07-05-34-613_de mm20 launcher2 release](https://github.com/ismartcoding/plain-app/assets/23485114/c9ee6fc7-63a7-46c8-b5bd-ba4adb99ecc3)

**Comment by ismartcoding** [comment]
I realized that I only implemented Monochrome support for the rounded icon, forgetting to include the regular icon. Will fix that in next release.

**Comment by xmha97** [comment]
Thanks

**Comment by ismartcoding** [comment]
Try the latest version.

**Comment by xmha97** [comment]
> Try the latest version.

![Screenshot_2024-04-02-23-36-30-845_de.mm20.launcher2.release.jpg](https://github.com/ismartcoding/plain-app/assets/23485114/ee16fc0a-d9ea-48e4-b024-1e850553af5a)

Thanks <3
