### ISSUE TITLE
The "apps" feature from sharex

### ISSUE THREAD

**Issue by Wjxfi** [ismartcoding/plain-app#16]
I saw a very similar app, and it has an "apps" function. It shows all the apps and lets you download them. It also shows the package name and size. It also has a search function. I would like to have this function in your app too.

https://www.f-droid.org/packages/com.akansh.fileserversuit/

![cc7edcb6-79d7-480c-95c5-308667561887.jpg](https://user-images.githubusercontent.com/113500363/233801240-c6614e9c-58d3-49be-9e89-c620b9f9c7cd.jpg)

**Comment by ismartcoding** [comment]
Added to  v1.0.18
