### ISSUE TITLE
能不能把markdown编辑器抽取成一个单独的lib组件

### ISSUE THREAD

**Issue by ldlywt** [ismartcoding/plain-app#164]
看了很多的markdown项目，觉得简朴的颜值最高。
能不能把它抽取成一个单独的组件，maven依赖？

多谢老哥开源

**Comment by ismartcoding** [comment]
抽取 lib 需要考虑定制化需求，会增加代码复杂度。我个人精力有限，建议有需要的话直接拷贝相应的代码到自己的项目中去能更好的定制化自己的需求。
