### ISSUE TITLE
Screen mirror resolution on Pixel Fold is unusable

### ISSUE THREAD

**Issue by molitar** [ismartcoding/plain-app#171]
**Describe the bug**
Screen graphics is awful it's even beyond pixelation awful that it is unusable can't tell what any icon is

**To Reproduce**
Share Screen on Pixel Fold when it's open 

**Expected behavior**
Screen looks like a 320 resolution and not able to make out any icons

**Screenshots**
Attached screenshot to show how bad it is

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Floorp
 - Version 11.12.2

**Smartphone (please complete the following information):**
 - Device: Pixel Fold
 - OS: Android 14
 - App Version: 1.2.48

**Additional context**
![Screenshot_2](https://github.com/ismartcoding/plain-app/assets/16074561/4f8275cf-8655-41a2-a7ef-8a5089571840)

**Comment by ismartcoding** [comment]
Check the latest version, I don't have a Pixel Fold to test.

**Comment by molitar** [comment]
OK the view has improved a bit now can make out icons but still bad.

![Screenshot_3](https://github.com/ismartcoding/plain-app/assets/16074561/ab93724e-f177-4a74-a0bc-48ed622bdcc0)

**Comment by ismartcoding** [comment]
Check the latest version, https://github.com/ismartcoding/plain-app/releases/tag/v1.2.50

**Comment by molitar** [comment]
Looks way better now.

![Screenshot_1](https://github.com/ismartcoding/plain-app/assets/16074561/55173112-c334-4f97-9b02-db5372990d7f)
