### ISSUE TITLE
Expose Service to WAN via Tunnels,Proxy,etc.

### ISSUE THREAD

**Issue by wlrmarl** [ismartcoding/plain-app#176]
**Is your feature request related to a problem? Please describe.**
Yes, Ability to not limit service to only Personal Hotspot and Wireless LAN means it can be exposed to internet easily. This feature is required such that this supports allowing connection to it against Wifi and Tethering.

**Idea**
Using Termux and Cloudflare tunnel to securely expose the service to WAN.
Using ngrok as well.

**Request**
-Allow Service to be served from request originating not from Wifi and Hotspot.
-A Open Port for Proxies.
-Allow Localhost connection.
-Allow CSRF if tunnnels are used.
-All host allowed to Connect to Service.

**Comment by ismartcoding** [comment]
The web HTTP service is currently configured to listen on 0.0.0.0, meaning it has no specific limitations regarding access. If you can ping the device, you should be able to access the service. I mentioned Wi-Fi or hotspot for non-technical individuals, as they might not grasp the concept of being on the same subnet.
