### ISSUE TITLE
Notes huge problems. Really problems

### ISSUE THREAD

**Issue by Wjxfi** [ismartcoding/plain-app#180]
After updating the notes editor it became much worse, when you flip the screen errors, ugly, it used to be prettier and better, the text is under that snippet above the keyboard, and it became problematic to use. It all makes the new notes style terrible, really. I want to help you. I really hate using it this way and you have a bunch of bugs to fix, I haven't even listed them all. Lots of bugs and problems... I don't know how to describe all the problems, there are a lot of them, sorry, sorry, sorry

**Comment by ismartcoding** [comment]
@Wjxfi Do you have any screenshots to help me understand the issues?

**Comment by ismartcoding** [comment]
@Wjxfi try [1.2.56](https://github.com/ismartcoding/plain-app/releases/tag/v1.2.56)
