### ISSUE TITLE
Bug or cybersecurity breach? All photos in device have been deleted.

### ISSUE THREAD

**Issue by Erz3** [ismartcoding/plain-app#181]
**Describe the bug**
All images have been deleted when I just was deleting an specific group with a specific tag (named "Borrar" in attached logs)

**To Reproduce**
1. On Files section create a tag
2. Then group some photos with this tag
3. Go to tag group and click "select all", and then again to select all photos from all pages in this group.
4. A few seconds later appear a popup with something like "time is over".
5. Like aparently files have not been deleted, repeat the step 3, 4 and 5.
6. 5 or 10 minutes later, all images in my device have been deleted. (including those without tag)

**Expected behavior**
Delete only photos with "Borrar" tag

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Browser: Firefox
 - Version: 115.11

**Smartphone (please complete the following information):**
 - Device: Realme X2
 - OS: Android 11
 - App Version: 1.2.52

**Additional context**
I was looking infomation in logs but It seems deletion action has not been register. Looking with Logcat Reader Professional reading (without root) logcat source, I have found just one kind of registry related with a fatal error in GPS deamon and nothing more, either for previous days. Is it normal that there are so few records in logcat? The next hours it have got so many different entries (apps, audio, UI,  another deamos, etc.).

Logs: [latest_02-06-2024.log](https://github.com/user-attachments/files/15526922/latest_02-06-2024.log)

**Comment by ismartcoding** [comment]
Currently, deleting all images with a specific tag results in the deletion of all images. I am really sorry for this stupid bug. I understand that this has disappointed all my supporters, and I am committed to fixing it promptly.

In the log file. you can search the keywords "deleteMediaItems".
