### ISSUE TITLE
Add a health check endpoint

### ISSUE THREAD

**Issue by anoop-b** [ismartcoding/plain-app#182]
**Is your feature request related to a problem? Please describe.**
Exposing a route like`/healthz` can help with monitoring services

**Describe the solution you'd like**
a `/healthz` endpoint that returns 200 OK

**Comment by ismartcoding** [comment]
Check this URL: http(s)://{ip}:{port}/health_check

**Comment by anoop-b** [comment]
Thank you, this helps.

Although i would prefer returning just "OK" or something similar, instead of the `com.ismartcoding.plain` . It's an avoidable attack vector, what do you think?

**Comment by ismartcoding** [comment]
The ID `com.ismartcoding.plain` is simply an application identifier used to differentiate between the debug version and the production version of the app for the HTTP server process. It has no relation to any form of attack.
