### ISSUE TITLE
How do I delete or add files?

### ISSUE THREAD

**Issue by 825i** [ismartcoding/plain-app#194]
**Describe the bug**
When using the app from a browser there's no delete button anywhere. Hitting DEL button on my keyboard also does nothing. I also cannot add any files using Plain. There's no way to add a file from my PC into Plain to be sent to my phone. 

**To Reproduce**
1. Open Plain
2. Go to the website
3. Pick a folder on phone storage
4. Can't delete any files in any folder
5. Can't add any files from my PC to the phone via Plain

**Expected behavior**
I can upload and delete any files. Similar to other WiFi sharing apps. 

Android 14
Xperia 1V
Plain v1.2.48

**Comment by ismartcoding** [comment]
Upgrade to 1.3.5 and try again.
