### ISSUE TITLE
Redmi Note 8 Pro crash on startup

### ISSUE THREAD

**Issue by r0msk1** [ismartcoding/plain-app#2]
Reposting my comment on Reddit, just a headsup. Thank you for this app.

RN8Pro crash on startup

https://freeimage.host/i/HkbwccG

**Comment by ismartcoding** [comment]
Duplicated: https://github.com/ismartcoding/plain-app/issues/1
I have uploaded the app 1.0(12) version to Google Play Store. Waiting for review.
