### ISSUE TITLE
Code source of the web app instead chunks in assets folder

### ISSUE THREAD

**Issue by antonymarion** [ismartcoding/plain-app#202]
**Is your feature request related to a problem? Please describe.**
Is there source code available of the web app that is used inside https://github.com/ismartcoding/plain-app/tree/main/app/src/main/resources/web ?

It would enable people to fork and make PR of it to improve/fix issues discovered on the web app.

For instance, I found that the mirroring does show a small (tiny) canvas when using landscape mode; which means we have to use portrait only.

**Describe the solution you'd like**
Possibility to have access to embedded web app source code

**Describe alternatives you've considered**
None possible as modifying bundled js code is not very user friendly (for devs)

**Comment by ismartcoding** [comment]
You can find the web source code here: https://github.com/ismartcoding/plain-web
