### ISSUE TITLE
Please prove that your site is safe (https problem).

### ISSUE THREAD

**Issue by Wjxfi** [ismartcoding/plain-app#22]
The dialogue where the problem is described is at the bottom.

***Create https server instead of http with aes 128 or 256 encryption and tls 3.0***

Look at how he did it
https://www.f-droid.org/packages/com.ismartcoding.plain/
https://www.f-droid.org/packages/org.localsend.localsend_app/

it may require a long password (for encryption)

--------------------

I'm guessing that for this to be practically possible, it would require the receiver to have the same app but in a state to receive.

As the main intent is for this to just work like by accessing via browser without installing a self-signed certificate, by default at least, it would not be possible. Maybe if a receive mode was implemented, that could be added as a way to help secure that connection. But there aren't currently plans lined up for that.

But honestly even so, it looks like it might be more of security theatre. For example, the private key is very present in the LocalSend app. There's some other things going on, so maybe that's at least preventing an attack in terms of MITM (provided the attacker isn't the intended receiver) to some extent -- don't quote me on that though. Either way, if I do add in support for encryption then I'd want to do that properly. I'm no cryptographer, so I don't have much of an idea of how to have something solid enough in this sort of situation.

-------------------

https://www.f-droid.org/packages/com.ismartcoding.plain/
this app works through the website and any apps the recipient doesn't need

---------------------

In the case of that, it prompts for the user to essentially trust the unsigned certificate in the browser.

---------------------

If the site is open source, you can trust it, I guess

---------------------

Ultimately, the issue is that as long as the network is untrusted, it's possible for the attacker to use their or the app's own self-signed to try impersonating the server. Encouraging users to trust an untrusted self-signed certificate isn't wise in general, and would be an inconvenience (i.e. would have to at least let them know that it won't generally be usable outside of a web browser, user has to perform an extra step to 'trust' something that may not be trustworthy).

The best way to go about this with how things currently are is to use mobile tethering. It would have its own LAN of which you can trust. The sender can be the device tethering but it will still be on its own network. Any device that joins that network can reach the sender. Mobile data doesn't need to be on for it to operate.

There's stuff such as WiFi direct that would help (although limited between Android devices), but the big issue I keep running into is scoped storage.
For some time, existing apps have to target 31 (Android 12) at least -- this is going to be increased further for new app publications and updates from 31st August 2023. The API limitations affects this app, as well as similar ones such as the ones you had linked to. They cannot perform efficiently (i.e. no direct access to selected files and so are copied to app's cache) or perform tasks that involve saving into a specific location under internal storage. Not without the functionality they depend on supporting the use of a permission that is strictly limited on Google Play (and even then, it has to meet the exceptions made).

**Comment by ismartcoding** [comment]
1. The HTTPS solution is better than NOTHING.
2. Open the `Open in PC web browser -> ... -> HTTPS certificate signature`, you can compare the signature value with the browser one if you really concern the security.
![image](https://user-images.githubusercontent.com/92670034/233877600-4c9889f3-456b-4f14-8778-429f8a0bc79e.png)
3. All data in the api request or response are encrypted. Nobody can even steal your phone data.
![image](https://user-images.githubusercontent.com/92670034/233877738-d1357424-49ae-4993-894b-b9481872c6e5.png)
4. Every file URL is encrypted with a file token which will be recreated when app restarts. When you share the file URL with someone, he will not be able to access that file if your app restarts.
5. Is there an existing solution which can hack the self-signed certificate solution? I would like to try to see if I can improve it.
