### ISSUE TITLE
Show files from external storage (such as SD cards)

### ISSUE THREAD

**Issue by naturalobject** [ismartcoding/plain-app#23]
**Is your feature request related to a problem? Please describe.**
Files and Audio can only display files in Internal storage. Images and Videos are able to display external storage contents with no issues.

**Describe the solution you'd like**
An option to browse files in external storage also

**Comment by locuturus** [comment]
And USB drives. With All Files Access this is all available, it just needs to be implemented.

**Comment by ismartcoding** [comment]
I am working on this.

**Comment by ismartcoding** [comment]
USB drive  will be supported in 1.1.15
