### ISSUE TITLE
see image and video and audio folders

### ISSUE THREAD

**Issue by Wjxfi** [ismartcoding/plain-app#28]
Now it's impossible to find what I need because everything goes in a row. All galleries have access to folders but not yours

The folder collects a lot of photos (and other things), it's very useful. I would also like to be able to create such folders in the app and add different photos (and other things) to them

folder photo:
![5b8b1c2a-764c-4252-9443-54bd517a3dd1.jpg](https://user-images.githubusercontent.com/113500363/235651297-433bbcbd-8403-49e2-9e30-4ef6d052dce3.jpg)

https://www.f-droid.org/packages/deckers.thibault.aves.libre/
https://www.f-droid.org/packages/com.simplemobiletools.gallery.pro/
https://apt.izzysoft.de/fdroid/index/apk/com.dot.gallery

**Comment by ismartcoding** [comment]
Hmm... I dropped the folder concept to make the UI clean and simple. You can see that all the data is designed to be organized using tags. Now, you are bringing back the folder again... That is not what I want.

You still can organize your media in Files explorer.

**Comment by ismartcoding** [comment]
Added in 1.1.15
