### ISSUE TITLE
I have a percistant hacker targeting system apps. No root, can't find recovery key for pc. After days of non stop trial an error I delete the infected apps. They returned ten min later. How to keep them gone?    P.s.- I'm begginer/intermediate level wth this stuff.

### ISSUE THREAD

**Issue by Logan1127** [ismartcoding/plain-app#41]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ismartcoding** [comment]
Maybe this repository can solve your issue. https://github.com/0x192/universal-android-debloater
