### ISSUE TITLE
it replaces rare characters in rss with incorrect ones

### ISSUE THREAD

**Issue by Wjxfi** [ismartcoding/plain-app#42]
![d2fc0c84-cf3a-442c-b6e6-fdc983227c04.jpg](https://user-images.githubusercontent.com/113500363/236616215-dfbaf092-fdd1-42da-85de-e996597b89dd.jpg)

**Comment by ismartcoding** [comment]
@Wjxfi What is the difference between these two images? I didn't get it.

**Comment by ismartcoding** [comment]
In Markdown, the character "-" will be rendered as a round object.
https://www.markdownguide.org/basic-syntax/#unordered-lists

**Comment by ismartcoding** [comment]
Will change the css style.
