### ISSUE TITLE
Translation into Spanish

### ISSUE THREAD

**Issue by AmadeusGraves** [ismartcoding/plain-app#44]
Hello, I have seen your application and I want to contribute by translating it into Spanish. I have the application installed and I see that it is available in 2 languages so it is internationalised, but I don't see where the languages are in the project. 

I have looked in the documentation and I don't see anything either. Can you tell me how I can translate this App into Spanish?

Best regards.

**Comment by ismartcoding** [comment]
https://github.com/ismartcoding/plain-app/issues/81
