### ISSUE TITLE
Button order

### ISSUE THREAD

**Issue by WizardOfXerox** [ismartcoding/plain-app#49]
Please reconsider the button order. mostly used button order for such this things is that "Save" button is first and "Cancel" button is last.
![image](https://github.com/ismartcoding/plain-app/assets/56929627/5fad4799-d866-4943-976b-c0290c3cacd7)

**Comment by ismartcoding** [comment]
No, cancel button should be on the left. Follow the material design specs.

![image](https://github.com/ismartcoding/plain-app/assets/92670034/32df685d-2f76-4859-8a75-9484a139a7dc)


https://m3.material.io/components/dialogs/specs

-----------
And the bootstrap demo also put the save button on the right.

https://getbootstrap.com/docs/5.3/components/modal/

![image](https://github.com/ismartcoding/plain-app/assets/92670034/7a6b3183-0e2e-473e-854d-1be2f30d66c6)
