### ISSUE TITLE
部分rss中全文图片无法正常显示，显示"OBJ"

### ISSUE THREAD

**Issue by Lao-Tz** [ismartcoding/plain-app#53]
rss中图片显示"OBJ"

To Reproduce
### Steps to reproduce the behavior:
1. 导入订阅源，此处我测试了
        科学网的订阅源:"http://www.sciencenet.cn/xml/paper.aspx?di=0"     **异常**
        豆瓣同城订阅源:"https://rsshub.app/douban/event/hot/108309"       正常
2. 针对科学网设置全文列表/正文中下拉获取全文(如果作者需要测试，请选择中文标题的文章，因为网站的原因，英文标题的文章会很快被删掉，如果没有第一时间缓存全文会无法显示)
3. 滚动到有图片的位置
4. 显示"OBJ"

### Screenshots
上传与inoreader的对比图

![inoreader](https://github.com/ismartcoding/plain-app/assets/93063057/1e0dbfb4-1efe-4e43-b354-3c1537ceacee)
![简朴](https://github.com/ismartcoding/plain-app/assets/93063057/8c429197-65b4-4fc9-bbb9-4200121e10b0)

### Smartphone (please complete the following information):**
 - Device: [坚果r2]
 - OS: [ Android 11]
 - App Version: [1.024/1.025]

**Comment by ismartcoding** [comment]
Fixed in 1.0.26
