### ISSUE TITLE
App crashes when clicking Settings 

### ISSUE THREAD

**Issue by itsarys** [ismartcoding/plain-app#57]
**Describe the bug**
Hello friend. I really appreciate you work on this program. It's good and simple to use application and almost works perfectly. The only issue is when i click on settings, the app just crashes and exits. I tried stopping the service, clearing data and re giving the permissions, none of them worked this far.

**Smartphone**
 - Device: galaxy tab a7 t505
 - OS: android 12
 - App Version: 1.0.25 arm64-v8a

**Comment by ismartcoding** [comment]
Can you upgrade the app to latest version 1.0.28?
 https://github.com/ismartcoding/plain-app/releases
