### ISSUE TITLE
Option to disable connection requests pop-up

### ISSUE THREAD

**Issue by itsarys** [ismartcoding/plain-app#58]
**Is your feature request related to a problem? Please describe.**
Hello friend. I work with many computers at a time so it's really tiresome and frustrating to come back to my phone and accept the connecting request pop-up everytime. It's a private LAN and i use the password option, so the requests are unnecessary for me.

**Describe the solution you'd like**
The option to completely disable the connecting request or temporarily for a set period of time.

**Comment by ismartcoding** [comment]
Hi, how many computers do you have? Why not using the no password option?

**Comment by itsarys** [comment]
> Hi, how many computers do you have? Why not using the no password option?

Up to 30. The no password option still needs to accept the connecting requests which is tiresome for that many computers.

**Comment by ismartcoding** [comment]
That's fascinating! So, are you planning to use this setup in a classroom where multiple PCs will simultaneously connect to a phone?

**Comment by ismartcoding** [comment]
Add "Require confirmation" option in 1.0.29.

![image](https://github.com/ismartcoding/plain-app/assets/92670034/bcd380f2-4dbc-4c48-9a26-9788203329dc)

**Comment by itsarys** [comment]
> That's fascinating! So, are you planning to use this setup in a classroom where multiple PCs will simultaneously connect to a phone?

Yes something like that but I am not goning to connect all of them simultaneously, because I still don't know the limitations. 



> Add "Require confirmation" option in 1.0.29.
> 
> ![image](https://user-images.githubusercontent.com/92670034/248197981-bcd380f2-4dbc-4c48-9a26-9788203329dc.png)

Thank you very much my friend you are making my life easier.
