### ISSUE TITLE
 PlainApp shows the 'wrong' IP address in the 'Open in PC web browser' UI

### ISSUE THREAD

**Issue by thomp** [ismartcoding/plain-app#62]
**Describe the bug**
On some Android devices, PlainApp shows the 'wrong' IP address in the 'Open in PC web browser' UI.

 **To Reproduce**
This is _not_ reproducible across multiple devices. It's a problem only on one of my Android devices. On another Android device, it is not an issue.

 1. Start PlainApp
 2. Click on the icon for the 'Open in PC web browser'
 3. The app UI shows https://192.0.0.4:8443 -- but the phone is at 192.168.254.35.

 Note: https://192.168.254.35:8443/ works fine for accessing PlainApp.

 **Expected behavior**
 IP address in the UI should be the address which "works".

 **Smartphone (please complete the following information):**
  - Device: U307AS
  - OS: Android 9
  - App Version: APK is 1.0.29

**Comment by ismartcoding** [comment]
It is likely that your device has multiple IPv4 addresses. I will handle this in the next version.

**Comment by ismartcoding** [comment]
Try 1.0.30 https://github.com/ismartcoding/plain-app/releases/tag/v1.0.30

**Comment by fpubio** [comment]
Thanks. This issue seems to be resolved.
