### ISSUE TITLE
Drag and drop for uploading files/folders

### ISSUE THREAD

**Issue by Savasdotexe** [ismartcoding/plain-app#66]
**Is your feature request related to a problem? Please describe.**
To upload a file you have to right click, find the file and select to upload. 

**Describe the solution you'd like**
A more simple method, drastically reducing the amount of clicks needed is to be able to drag and drop.

**Describe alternatives you've considered**
Not really any alternative than manually doing it or using another app.

**Additional context**
This is especially useful for when you've got a file buried in a folder somewhere and trying to locate to upload it is a massive pain, drag and drop would mean you avoid all of that. I guess the most simplest method is to have a static spot for where drag and drop works. Or ideally make it possible to drop a file in the folder and the rest of the page becomes darker.

P.S. thank you for a great app.

**Comment by arnabs542** [comment]
+1 It will be great feature add.

**Comment by ismartcoding** [comment]
Fixed in 1.3.0 release
