### ISSUE TITLE
Can't open "JPG" extension images, only "jpg"

### ISSUE THREAD

**Issue by luispinho** [ismartcoding/plain-app#73]
**Describe the bug**
In the "Images" tab, I can see all the images' thumbnails on my device (including /DCIM/Camera and /Pictures).

When I try to open any image which extension is "JPG" (uppercase) the image does not open. I am, however, able to open "jpg" images with no issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Images' tab
2. Click on any image with extension "JPG" (uppercase)
3. Loading spinner shows but never loads the image (do notice that the name of the picture also does not appear in the webpage header, unlike the other images)

**Expected behaviour**
Clicking on any image shown in the thumbnail grid should open successfully. 

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: MacOS 13.14.1
 - Browser: Brave and Chrome ([1.52.129 Chromium: 114.0.5735.198 (Official Build) (arm64)])

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android 13 (LineageOS 20)
 - App Version: 1.1.6

**Possible solution**: Consider making the `PHOTO_EXTENSIONS` list in `Constants` case-agnostic (or in all usages of this list). That should likely fix the issue for all file extensions.

**Comment by ismartcoding** [comment]
Fixed in https://github.com/ismartcoding/plain-app/releases/tag/v1.1.17
