### ISSUE TITLE
I want to make a Spanish translation

### ISSUE THREAD

**Issue by PinkLittleKitty** [ismartcoding/plain-app#81]
Hey! I have been wanting to translate this app to spanish, could someone point me in the right direction?
I just want to help, but not really sure where I can find the corresponding files.

(Sorry for opening an issue for this, but I don't know any other way of contacting ismartcoding)

**Comment by ismartcoding** [comment]
I have added the Spanish translation to the project. ChatGPT did the job.

https://github.com/ismartcoding/plain-app/blob/main/app/src/main/res/values-es/strings.xml
https://github.com/ismartcoding/plain-web/blob/main/src/locales/es.ts

**Comment by ismartcoding** [comment]
Supported in 1.1.9 https://github.com/ismartcoding/plain-app/releases
