### ISSUE TITLE
Request for Storage and Notes

### ISSUE THREAD

**Issue by manggo-zheng** [ismartcoding/plain-app#83]
Sometimes I don't need to operate my phone's storage because it's messy.
I only need a USB drive, and when I enter the web interface, I can directly click on the 'USB drive' button to enter the folder I need.
This requirement is somewhat similar to file favorites。

---

I hope to be able to edit tags in the note editing interface because the note list interface is too messy for me to find the note I want to edit the tag for.

---

Because I am lazy, I am too lazy to enter a password.
I think entering a password on a computer is not intuitive because we still need to confirm it on our phone.
And the password is also random, and in the second level interface, the final one is ciphertext, which is too uncomfortable. I have to check my password every time I use the software.
Actually, just keep the steps for confirming login with your phone.
---

Finally, thank you for your work, allowing me to deploy a note server on the phone I carry with me.

**Comment by ismartcoding** [comment]
You can choose "No password" option and turn off "Require confirmation".
