### ISSUE TITLE
When uploading files from the web side, an additional folder with the same name will be created.

### ISSUE THREAD

**Issue by Faserr** [ismartcoding/plain-app#87]
**Describe the bug**
As the title indicates. I don't know how to edit the code because it looks like it's been mixed up. In addition, I think the Web-side file interface needs a refresh button, because when I upload or update files, I always need to refresh the entire webpage.

**To Reproduce**
1. Go to 'My Phone' inWeb
2. Click 'Upload file' button to upload a file
4. There was an error in the result: as shown in the screenshot, a folder with the same name was generated

**Screenshots**
![image](https://github.com/ismartcoding/plain-app/assets/46740335/e590d472-8755-484e-a071-f9d58ea0fb7a)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]

**Smartphone (please complete the following information):**
 - Device: Windows 11
 - OS: Android-10_HarmonyOS-3
 - App Version: 1.1.15(107)

**Comment by ismartcoding** [comment]
1. "There was an error in the result: as shown in the screenshot, a folder with the same name was generated"
I can reproduce this one, will fix it in 1.1.16.

2. "I think the Web-side file interface needs a refresh button, because when I upload or update files, I always need to refresh the entire webpage."
Did you mean the Files page is not updated or the "My phone" window is not updated?

**Comment by Faserr** [comment]
> 2.您的意思是“文件”页面未更新或“我的手机”窗口未更新？

This issue primarily appears on the web. For example:

1. When I open the "com.ismartcoding.plain/files/" directory and upload files through "My Phone", the webpage does not update.
2. When I use other apps to move files, the directory still cannot be updated.


In this away, need to refreshing the webpage can the directory be completely updated.

**Comment by Faserr** [comment]
Thank you for your contribution!

Can I directly paste pictures by pressing Ctrl+V? It would be great if I can drag and drop files to send them through the web. I often need to send screenshots to the window. I used the Wechar-web version before, but when transferring images through WeChat, they are converted to webp, which is not a good experience.

I'm not sure if I need to create a new issue.

**Comment by ismartcoding** [comment]
Got it. No problem. Paste and drop files will be supported in 1.1.17

**Comment by Faserr** [comment]
> Got it. No problem. Paste and drop files will be supported in 1.1.17

Very, very grateful!!!!!!!!!!!!!  XD
