### ISSUE TITLE
启用不了http服务，请问如何解决

### ISSUE THREAD

**Issue by gongqf** [ismartcoding/plain-app#89]
![Screenshot_2023-08-31-00-19-41-587_简朴](https://github.com/ismartcoding/plain-app/assets/751931/776c4bb3-155a-42dd-b3ab-ee59f2b78cb3)
![Screenshot_2023-08-31-00-19-54-686_简朴](https://github.com/ismartcoding/plain-app/assets/751931/b056f2b9-4f6b-47c4-8fba-0d96fa2dcce7)
![Screenshot_2023-08-31-00-22-16-290_简朴](https://github.com/ismartcoding/plain-app/assets/751931/75e73988-6bd8-47c0-85a7-2312edca7463)

锤子坚果r2手机，安卓11版本，googleplay下载版本

**Comment by ismartcoding** [comment]
http port 和 https port 都更改一下。

**Comment by gongqf** [comment]
第二天用就正常了。也没改过端口。

**Comment by gongqf** [comment]
用1.2.5版还是会出现这个问题。而且那个重启应用按钮不管用。具体现象是这个lan内当天第一次访问一般正常。等过一会，手机开启clash后web链接会断开，plain也会改变ip地址。断开clash后就一直无法链接了，重启手机，重启浏览器都无效

**Comment by ismartcoding** [comment]
PlainApp 不会修改手机IP 地址，它用的是你的手机地址。Android Debug Database这个是哪个 APP 开的网页服务？
java.net.BindException: Address already in use 这个错误说明端口冲突了。把 HTTPS 和 HTTP 端口都改成其他的端口，避免使用 8443，8080。
