### ISSUE TITLE
通过web端的对话功能向手机发送图片或者文件，在手机端没办法找到

### ISSUE THREAD

**Issue by 361292623** [ismartcoding/plain-app#90]
**Describe the bug**
app版本：1.1.19
通过web端的对话功能向手机发送图片或者文件，在手机端没办法找到，不知道写到哪个目录了，但是在备份应用数据导出出来的压缩包里却可以找到。

**Comment by ismartcoding** [comment]
点击 Files 页面左边 PlainApp 这个选项

**Comment by 361292623** [comment]
感谢大佬回复

**Comment by 361292623** [comment]
> 点击 Files 页面左边 PlainApp 这个菜单选项

感谢大佬回复

**Comment by gongqf** [comment]
> **Describe the bug** app版本：1.1.19 通过web端的对话功能向手机发送图片或者文件，在手机端没办法找到，不知道写到哪个目录了，但是在备份应用数据导出出来的压缩包里却可以找到。

请问怎么通过web的聊天框向手机app发送图片、视频等。我只能通过app向web发送图片、视频。

**Comment by ismartcoding** [comment]
1.1.19及以上版本才支持。
点图片中这两个按钮或者复制粘贴图片、文件到文本框里面。
![image](https://github.com/ismartcoding/plain-app/assets/92670034/0432e301-c778-4e7f-a3c2-3813e0f4eb22)

**Comment by ywgdjryf** [comment]
> 点击 Files 页面左边 PlainApp 这个菜单选项

这个东西在哪??

**Comment by ywgdjryf** [comment]
在手机端真的没有
![image](https://github.com/ismartcoding/plain-app/assets/149993388/d3fd85f0-1281-4547-9979-943d401dbb78)
目前只能通过设置-备份与恢复，在压缩包文件找到，点快了设置还容易卡死，问题是真的多
