### ISSUE TITLE
通过web端向手机传输大型文件，如大小3GB以上的视频文件时，app有可能崩溃退出或者卡死

### ISSUE THREAD

**Issue by 361292623** [ismartcoding/plain-app#91]
Describe the bug
app版本：1.1.19
通过web端向手机传输大型文件，如大小3GB以上的视频文件时，app有可能崩溃退出或者卡死，导致传输中断，目前只测试了小米13 ultra一台手机

**Comment by ismartcoding** [comment]
无法复现，没有可以优化的点，跟设备性能或者存储空间不足有关。

**Comment by ismartcoding** [comment]
1.2.2已优化支持分块传输文件。
