### ISSUE TITLE
加一个上传按钮

### ISSUE THREAD

**Issue by Diddian** [ismartcoding/plain-app#92]
目前，Mac用户可以通过右键单击来上传数据，但iPhone用户却不能这样做。这让直接从iPhone发送照片到Android设备变得有些困难。我想提一个小小的请求：能否在打开特定文件夹时添加一个上传按钮？(上传的路径应该是最新打开的子文件夹吧, Floating button like "My phone"。

希望您能考虑这个改进，使得PlainApp更加完善和用户友好。

感谢您的努力和贡献！

**Comment by ismartcoding** [comment]
Fixed in 1.3.0 release
