### ISSUE TITLE
Screen mirror

### ISSUE THREAD

**Issue by EraNetGit** [ismartcoding/plain-app#96]
First thing, I would like to say that you have created a great app with some great features. Well done. 👏

I am not sure if this has already been requested, but I would love to have the option in screen mirror, to be able to control my mobile from my PC, so to be able to open/close apps, click the home button, check notifications, etc.

Keep up the good work.
Regards,
Eran

**Comment by ismartcoding** [comment]
I'm not sure if anyone else shares the same requirements, but I believe using a mouse to control your phone from a PC may not be very practical or user-friendly. I can add the notifications feature on web UI.

**Comment by EraNetGit** [comment]
I'd be happy to be able to have some control over my phone from my PC, this way I won't even need to touch it when working on my PC. Having two modes, view only & full control would be great. :-)

**Comment by ajmz** [comment]
> I'm not sure if anyone else shares the same requirements, but I believe using a mouse to control your phone from a PC may not be very practical or user-friendly. I can add the notifications feature on web UI.

Same requirement for me.

**Comment by 123jrh** [comment]
I don't know what permissions screen mirroring needs to be enabled, I enabled some permissions but still don't work

**Comment by ismartcoding** [comment]
@123jrh Please add the QQ group 812409393 for support.

**Comment by ismartcoding** [comment]
https://github.com/ismartcoding/plain-app/issues/174
