### ISSUE TITLE
F-Droid apps

### ISSUE THREAD

**Issue by EraNetGit** [ismartcoding/plain-app#97]
Hi,

I was wondering if it would be easy to add in the Web PlainApp, under Storage --> Apps, the option to list F-Droid apps separately.

When reinstalling an Android phone, it is easy to restore Google Play Store apps, but there is no way to restore F-Droid apps, so having F-Droid apps listed separately will enable me to also easily back them up.

I saw online a suggestion to do the below and was wondering if this will help you achieve this filter:

Write list of apps to file
adb shell "pm list packages" | sed 's/^package://' > installed_apps.txt

* Download and install each app in app list to device
while read -r app; do
suggested_version_code="$(curl "https://f-droid.org/api/v1/packages/${app}" | jq -r ".suggestedVersionCode")"
curl "https://f-droid.org/repo/${app}_${suggested_version_code}.apk" --output "${app}.apk"
adb install "${app}.apk"
done < installed_apps.txt

Anyway, thank you for considering this.

**Comment by ismartcoding** [comment]
It will be searchable by "fdroid" in 1.2.5

![image](https://github.com/ismartcoding/plain-app/assets/92670034/871d92f1-3d17-46e4-982f-4f1939a42610)

**Comment by EraNetGit** [comment]
Amazing! Thank you for that.
