### ISSUE TITLE
Exchange rate - stopped working

### ISSUE THREAD

**Issue by EraNetGit** [ismartcoding/plain-app#98]
Hi,
I'm not certain if I'm doing something incorrectly, but I have tested the 'Exchange rate' tool in the bellow versions, and it appears to have ceased functioning on my Samsung Galaxy S22+, all I see is 'Exchange rate' and no rates are showing, just black.
Release 1.2.4
Release 1.2.3
Release 1.1.22

Thanks.

**Comment by ismartcoding** [comment]
The free API https://api.exchangerate.host/latest stopped working. https://github.com/exchangeratesapi/exchangeratesapi

**Comment by ismartcoding** [comment]
The service is back up now.

**Comment by Universal-Igloo** [comment]
Sorry, but the service is not back up. I am on the latest update, but exchange rate never works anymore. Just shows a blank screen that says "Exchange Rate". (Screenshot attached)

![Screenshot_20231006-025238](https://github.com/ismartcoding/plain-app/assets/95539123/5af864fa-b15d-41a8-859e-5bc639edfe7d)

**Comment by ismartcoding** [comment]
The API is no longer free to use. I have to switch to another free API.
