### ISSUE TITLE
File management issue

### ISSUE THREAD

**Issue by RedCrafter07** [ismartcoding/plain-app#99]
**Describe the bug**

Hello.
I just went to the web dashboard and deleted an old audio file from it before uploading a new one. I selected the one file I wanted to delete. However, it deleted all my audio files on my phone, forever. I can't get them back anymore.

**To Reproduce**
1. Go to Audio on the web dashboard
2. Click on any audio file and delete it
3. all files get deleted after some time
(it happened for me for the first time, I've tried it before and it worked normally)

**Expected behavior**
Deleting all files instead of all

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave, based on chrome
 - Version 1.58.131

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note10 Lite
 - OS: Android 13
 - App Version: 1.2.5

**Comment by ismartcoding** [comment]
Sorry to hear that. I just tried but couldn't reproduce this. Is this reproducible on your side? Maybe a video some screenshots can help me reproduce this?

**Comment by ismartcoding** [comment]
Sorry to hear that. OMG, you are a  life saver. This happens when click the delete button twice.

**Comment by RedCrafter07** [comment]
I was able to restore the important files somehow, thanks for fixing, I hope I could help so this doesn't happen to others :)

**Comment by ismartcoding** [comment]
I hope this won't happen to others...

**Comment by RedCrafter07** [comment]
Yes, but it's fixed, so that's good.
Another suggestion I'd make is to move them to the recycle bin instead of permanently deleting them. That way, users can change their minds after deleting files (like in other file management systems), and such problems wouldn't be as critical as the files could be easily recovered.
